### ISSUE TITLE
(#104) Patch Requests are failing. None of the patch requests are going through.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#65] opened 2017-01-11 18:33 UTC
(#104) Patch Requests are failing. None of the patch requests are going through.

The patch requests are not going through. Please find below the screen shot of the same-
*Step1: Patch call with indicator flags as false*

![step 1](https://cloud.githubusercontent.com/assets/8714134/21861342/d1354750-d80a-11e6-819d-e914d02e373e.png)

*Step2: Note that that when we do the get call for the delivery id, it is false.*
![step 2](https://cloud.githubusercontent.com/assets/8714134/21861344/d2cf3be8-d80a-11e6-8efe-5f904bf4053f.png)

*Step3: In the Ipad, note that the id image required and signature required flags are still required.*
![step 3](https://cloud.githubusercontent.com/assets/8714134/21861346/d50fb4dc-d80a-11e6-9fd5-75c7c7aaea9b.png)

**Comment by jasonmadrid** [comment] 2017-01-15 23:21
Verified that individual PATCH requests are working. #24, #25 & #49 detail the need for better bulk handling.

**Comment by brprashanth** [comment] 2017-01-16 18:51
The patch requests are still failing.
We found today that it fails when the Delivery Prescription has 1 or more customer listed that is different from the Recipient information. 

See the screenshots below.
*External ID: 31044.*
Please refer the request and response. 
[patch request.txt](https://github.com/rxtrax/tracking/files/709166/patch.request.txt)
[Uploading response.txt…]()

![patch failed](https://cloud.githubusercontent.com/assets/8714134/21995426/407c2112-dbfb-11e6-9178-dcc7b6bc0d1e.png)

![img_4989](https://cloud.githubusercontent.com/assets/8714134/21995433/4587948e-dbfb-11e6-8c50-2d6df3ec57d4.PNG)
![img_4990](https://cloud.githubusercontent.com/assets/8714134/21995434/45a727fe-dbfb-11e6-9f5d-48594613e760.PNG)

**Comment by RyanNerd** [comment] 2017-01-16 19:42
@brprashanth the attached request text file is for a delivery that was completed on 2014-07-14 14:33:12. Completed deliveries **can not be changed** (the API will return an error message now when this is attempted).

Do you have an example of failed update on a delivery that is not marked as delivered?

```JSON
{
	"external_id": "31044",
	"external_route_id": "1",
	"delivery_date": 1484505000,
	"deliver_before": "09:24 PM",
	"deliver_after": "06:24 PM",
	"photo_id_required": false,
	"reschedule": false,
	"signature_required": false,
	"recipient_photo_required": false
}
```

**Comment by brprashanth** [comment] 2017-01-16 19:52
Thanks Ryan for the clarification.
In either case, the application should have reported with an error saying the Patch failed for so and so reason.
The patch request just reported success and does not made any changes to the delivery.
Please shoot out an error message if it it cannot make an update with a reason.

Also, I will test it once with a fresh delivery.

**Comment by RyanNerd** [comment] 2017-01-16 19:58
@brprashanth Issue https://github.com/rxtrax/tracking/issues/45 addresses the patch failed issue for completed deliveries, but this has not been pushed to sandbox yet.

**Comment by RyanNerd** [comment] 2017-01-16 22:10
Tested with the following request changing the `photo_id_required`, `signature_required`, etc. fields and made sure the iPad updated with the changes. There is an expected small delay between the PATCH and the iPad update. But every patch test worked. I completed the delivery and tried to patch the delivery which now responds below:

Request:

```json
{
	"external_id": "587d3d1a9de24",
	"deliver_before": "10:23 PM",
	"deliver_after": "08:24 PM",
	"photo_id_required": false,
	"reschedule": false,
	"signature_required": true,
	"recipient_photo_required": false
}
```

Response:

```json
{
  "success": false,
  "code": 400,
  "data": null,
  "message": "Invalid request.  Check missing parameters section of response.",
  "missing": {
    "invalid": {
      "587d3d1a9de24": "immutable_delivery"
    },
    "optional": {
      "instructions": "string",
      "collect_amount": "float",
      "delivery_date": "datetime",
      "original_delivery_date": "datetime",
      "cancelled_on": "datetime",
      "address1": "string",
      "city": "string",
      "state": "string",
      "postal_code": "string",
      "payment_required": "boolean",
      "is_archived": "boolean",
      "en_route": "boolean",
      "collect_info": "json",
      "route": "Route",
      "external_route_id": "external_reference",
      "delivery.external_route_id=>delivery_date": "route_available",
      "recipient": "Customer",
      "external_recipient_id": "external_reference",
      "acknowledgements": "array[Acknowledgement]",
      "acknowledgement_ids": "array[string]",
      "prescriptions": "array[Prescription]",
      "delivery_prescriptions": "array[DeliveryPrescription]"
    }
  }
}
```

**Comment by brprashanth** [comment] 2017-01-17 15:24
Please find few more details on this patch request that is failing.
Note that this PATCH are failing now with DEV API Key however it is working with QA key API key.

API key: 
dev - anmdJdLYuYBe8U2qTARqrFjtB0uYQHUEkJnDmhsnsgJ4ucKVL7Zg
qa - hh09WTF1hT2YYYMRkRdmwSG6s4ojG4f1nK64dKSFYPSAg5Ql9w

NOTE: We have absolutely made sure this time that this delivery was not deleted/completed/finished

Request & Responses:
[response.txt](https://github.com/rxtrax/tracking/files/711464/response.txt)
[patch.txt](https://github.com/rxtrax/tracking/files/711465/patch.txt)

Steps:
We have followed the below process to initiate a patch response but still the patch was not working from offshore registers for Dev api key. 
1)	**External ID 93055** : Made sure this does not exist in the system.
Checked the get response for an receipt before posting an delivery and found that the receipt number was not used before. 
 ![image](https://cloud.githubusercontent.com/assets/8714134/22026476/46c4e78c-dca7-11e6-833b-86a4972e31b7.png)

2)	Posted a NEW Delivery with External ID 93055 and made sure it shows up on the IPAD.

3)	Sent PATCH Request: 
In Initial request  we did not set  delivery signature, Photo id and Recipient image to required. When we set them to true and sent an patch request . The ipad did not reflect the changes. Please find the patch request attached.
Patch Request
![image](https://cloud.githubusercontent.com/assets/8714134/22026501/5dd76508-dca7-11e6-94c1-c0940485bb8a.png)


Ipad Screenshot after patch request . The required flags did not show up in the ipad after syncing.
![image](https://cloud.githubusercontent.com/assets/8714134/22026515/66eb88ea-dca7-11e6-9131-04a45879fc8f.png)
 

4)	However the get response(URL- https://api.sandbox.getrxtrax.com/v1/deliveries?api_key=anmdJdLYuYBe8U2qTARqrFjtB0uYQHUEkJnDmhsnsgJ4ucKVL7Zg&external_id=93055&_ext=acks%2Ctxns) contains the values that we have sent in the patch request. Please find the get response attached.
 
![image](https://cloud.githubusercontent.com/assets/8714134/22026534/70bc3c16-dca7-11e6-8923-04faf40b43e9.png)

**Comment by RyanNerd** [comment] 2017-01-17 23:13
> Note that this PATCH are failing now with DEV API Key however it is working with QA key API key.

This is because each API key is representative of an individual pharmacy. And by design each pharmacy **can not access** deliveries in a different pharmacy.

**Comment by brprashanth** [comment] 2017-01-18 00:30
@RyanNerd we know how the API key works. Integrating with external systems are not new to us.

@jasonmadrid, @RyanNerd 
We took a lot of time to test, reproduce the issue, take screenshots and document.
Request you to go through and  review our findings. Please see the results from our testing redone from today.

**Comment by RyanNerd** [comment] 2017-01-18 15:47
I have started the process of attempting to reproduce (and trace through) the issues you have documented. My last comment was not meant to short circuit your testing. I appreciate your thorough testing and documenting. 
As you stated this takes some time, and perhaps even more so when I am stepping through the code to make sure any defects can be identified and fixed. Thanks.

**Comment by RyanNerd** [comment] 2017-01-18 18:04
@brprashanth 
Can you check the RxTrax version on the dev and qa iPad?
The latest is 4.0.0 (0.9.0)
This may be an iPad syncing issue.

**Comment by brprashanth** [comment] 2017-01-18 19:07
@RyanNerd - sure. I will check and confirm. Thanks.

**Comment by jasonmadrid** [comment] 2017-01-23 00:16
OK, after some code changes, I've tested all of the scenarios provided above and verified that PATCH updates are working in each case.  I'm going to close this again now, and hopefully we've taken care of this.  If it's still a problem, I think @brprashanth and I need to get on a call and demonstrate the problem.

**Closed by jasonmadrid** 2017-01-23 00:16 UTC
Labels: bug, high, needs_verification, pharmaserv, reopen

**Comment by brprashanth** [comment] 2017-02-02 03:44
This has been fixed.
